server:
  port: 8080

#change profile to 'prod' if you want to use mysql database (don't forget to start related container using docker-compose up -d)
spring:
  jpa:
    defer-datasource-initialization: true
    generate-ddl: false
    hibernate:
      format_sql: true
      show-sql: true
      default_schema: appDb

logging:
  file: app.log
  level:
    com:
      bookstore:
        springframework: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html